### ISSUE TITLE
Improve "Site down" experience in general (e.g. 404s)

### ISSUE THREAD

**Issue by michaelhidalgo** [mozilla/http-observatory#104]
Hello,
I was testing one of the domains whose IIS had a HTTP redirection when you navigate to the root (i.e when you browse to www.example.com). In spirit of not showing the IIS landing page, then a HTTP 301 was implemented.
However, during the deployment the redirection was not set and the server throws a HTTP 404, I got the message indicating that the site was down from Observatory.

I have a couple of questions here:
- Is that Ok that the tool cannot scan the domain when a HTTP 404 is presented? I wonder if the cipher suites test can/should be performed at least?
- Should the HTTP headers analysis be performed? Eventually if you do a HTTP HEAD then you should have a picture of what headers are exposed even when there is a HTTP 404

I appreciate your feedback!.

**Comment by marumari** [comment]
Yeah, the tool currently lumps a lot of stuff into "site down" because I didn't have the time to break it out into more detailed errors.

The cipher scans can definitely be done even with a 404 error; it's just that the website is behaving badly in that case.  I'll look into fixing that.

As for the tests, some of them could certainly be done (such as the headers), but a lot of them don't work at all (such as the SRI test) in the case of 404s.  Nevertheless, I shall think about how I can improve the experience in general there.  :)

**Comment by michaelhidalgo** [comment]
thanks for the information, April. Good stuff releasing this tool.

I'll try to get some spare time and start collaborating.

**Comment by april** [comment]
This is quite old and the site has changed a lot, so I'm gonna close this one.  :)
