### ISSUE TITLE
Return third party scan results in API

### ISSUE THREAD

**Issue by JochbertBendler** [mozilla/http-observatory#119]
It'd be nice if one could retrieve the third party scan results that have been done by the observatory from the API as well.
They're available on the website, but apparently not from the API.

**Comment by marumari** [comment]
Yeah, it's because the website queries their APIs directly.  The Observatory scanner itself doesn't talk to the APIs so that it can return results faster.  I do talk on the FAQ about who operates those APIs, so your best bet is to contact them and ask to integrate with them.  :)

Unfortunately, because of this design, I can't really fix this one.  Sorry!

**Comment by JochbertBendler** [comment]
Thank you for the clarification and quick answer.

I get now that it isn't possible on the http-observatory site of things; but wouldn't it be possible to have the website return the third-party results via API then, since it's also the one querying them?
Read: Would it make a difference if I opened this ticket as an issue on the website-project again?

Thanks in advance!
