### ISSUE TITLE
sri-not-implemented-and-external-scripts-not-loaded-securely has the wrong score

### ISSUE THREAD

**Issue by ekr** [mozilla/http-observatory#122]
https://github.com/mozilla/http-observatory/blob/master/httpobs/scanner/grader/grade.py#L237

Currently the observatory scores https: subresources w/o SRI at -20 and http: subresources at -50.

These scores don't seem to reflect a reasonable security assessment. We can debate the value of SRI, but because browsers (or at least any browser that supports SRI) don't load active mixed content, an http: subresource is basically a broken link, which is more secure than the https: subresource, which is a potential security issue (at least within the SRI threat model). And of course if the main page is http: then SRI doesn't help. At minimum these scores should be the same and arguably the http: one should be a less serious demerit

**Comment by ekr** [comment]
oops, https subresources w/o SRI is -5. I think this makes the point even stronger.

**Comment by marumari** [comment]
I'm not sure I agree with your assumption that SRI doesn't help if the primary page is http?  What if there's a MitM between myself and the CDN, but not one between myself and the origin?  Or what if there's no MitM, but the CDN got compromised? In both cases, SRI offers a level of protection, even if everything is over http.

The scores are just as much about risk as they are about getting people to fix their stuff. Even if modern browsers won't load http subresources from https, it's a broken design and this is a way to help people notice it, hence the -20 and the dropping of a full letter grade. Mixed content indicators in browsers help, and I'm hoping that this will help as well.

As for the -50, the reason why it gives -50 is to specifically make it impossible to get a non-failing grade unless your site uses https.  That is to say, no matter how much you muck around with CSP and SRI and everything, if you don't use https you can't pass (or otherwise get a decent grade).  Looking at the results that I've seen, that seems to be the case. So the -50 here is not so much about http -> http subresources, but about not having https in the first place.  :)

**Comment by ekr** [comment]
> I'm not sure I agree with your assumption that SRI doesn't help if the primary page is http? What if there's a MitM between myself and the CDN, but not one between myself and the origin?

This seems like an extremely unrealistic threat model given actual network deployments.

>  Or what if there's no MitM, but the CDN got compromised? In both cases, SRI offers a level of protection, even if everything is over http.



> As for the -50, the reason why it gives -50 is to specifically make it impossible to get a non-failing grade unless your site uses https. That is to say, no matter how much you muck around with CSP and SRI and everything, if you don't use https you can't pass (or otherwise get a decent grade). Looking at the results that I've seen, that seems to be the case. So the -50 here is not so much about http -> http subresources, but about not having https in the first place. :)

**Comment by marumari** [comment]
Please open up a bug to add a mixed content test.  I think it's a great idea.
