### ISSUE TITLE
Show hidden (or not) on scan results page

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/http-observatory#175]
Minor issue, but I think the SQL for `getRecentScans` might be out a little bit:

https://github.com/mozilla/http-observatory/blob/master/httpobs/database/database.py#L220

For example:

https://observatory.mozilla.org/analyze.html?host=code-poets.co.uk
Score: 135/100

https://http-observatory.security.mozilla.org/api/v1/getRecentScans?num=100&min=135

I must admit it's a little late on a Friday night to work out what's wrong though.

**Comment by marumari** [comment]
If you go directly to the analyze page, it automatically submitted as a "hidden" scan, since there isn't any point where you can state whether you want it hidden or not.  If you go to the home page and submit from there, it should appear in that list, but getRecentScans only shows recent non-hidden scans.

Could you test that way and let me know if you still have that problem?  If so, I'll dig into why it's happening.  :)

**Comment by craigfrancis** [comment]
Good point I did the rescan from the results page, so it would have been hidden.

Not sure if this would be useful, but could there be a line below the Scan ID saying the state of the Scan? And if it was "hidden", maybe the the word "hiddden" could be in bold?

**Comment by marumari** [comment]
That's a great idea.  I'll try to get that added this week.  :)

**Comment by april** [comment]
I actually did this ages ago but forgot to close the bug.  :)
