### ISSUE TITLE
Problem with the "Redirection" in the http header testing result

### ISSUE THREAD

**Issue by wanshuo168** [mozilla/http-observatory#180]
I found a problem that the "Redirection" results are different when scan the same website. 
One is scan "www.test.com", and the other one is "www.test.com:80". 
I think they are the same target, but the results are different: the "Redirection" result shows "Pass" when scan "www.test.com", but "Failed" when scan "www.test.com:80".
The problem seems like a bug I think.
@marumari , could you please check this issue, and fix it if it's a bug?
Thank you very much!

**Comment by marumari** [comment]
I'll take a look.  Thanks for letting me know!

**Comment by floatingatoll** [comment]
I wasn't able to trigger a scan of "www.test.com:80" at the public observatory website:

```Error: Www.test.com:80 is an invalid hostname```

@wanshuo168, how are you initiating the scan to "www.test.com:80" - as in, what command line, or lines in a script are you using? It's possible that the port has to be passed as an argument somehow, rather than using the appended ```hostname:port``` style.

**Comment by aosdf6dd** [comment]
I was about to submit a new issue,  but I think it could be the same as this one.

I scanned an application resulting in the following output:
![1482334381](https://cloud.githubusercontent.com/assets/20280659/21395133/a1168c2a-c79b-11e6-9713-46c87922f527.png)

The result says that the initial redirect is to a different host, although it is not. I guess you need to trust me that the domains behind the red boxes does exactly match :) 

It might be, that the attached port number confuses the check, as the redirect is not to "https://page.com" but "https://page.com:443".

The following screenshot shows the raw HTTP response of the initial request to HTTP:
![1482334381](https://cloud.githubusercontent.com/assets/20280659/21395232/02bd82ee-c79c-11e6-9236-01008db692ad.png)


best regards!

**Comment by floatingatoll** [comment]
Same question applies to you, too: In what manner did you scan the destination with port 443? What specific command line or other code did you use to invoke the scanner with the attached port number?

**Comment by floatingatoll** [comment]
I opened #192 to just outright refuse hostnames that end in a port number in the local scanner, since that's presumably the ingress point for the bad data. This doesn't address whether scanning of custom ports should be permitted; it only addresses the need to stop accepting invalid hostnames, so that we stop providing broken results when the scan() function is called incorrectly.

**Comment by aosdf6dd** [comment]
I never put a port number in the domain part, I always passed it separately via the http/https port parameters

**Comment by floatingatoll** [comment]
Hm.

So, you called ```scan('www.test.com');``` and it worked; and ```scan('www.test.com', http_port=80);``` and it failed?

Or, you called ```httpobs-local-scan www.test.com``` and it worked; and ```httpobs-local-scan --http-port 80 www.test.com``` and it failed?

Or, you called ```httpobs-local-scan http://www.test.com``` and it worked; and ```httpobs-local-scan --http-port 80 http://www.test.com``` and it failed?

**Comment by aosdf6dd** [comment]
Hm, now I'm not sure anymore whether the issue reported by @wanshuo168 is the same as mine.

I personally was launching a scan via _scan('www.test.com', https_port=443)_. Observatory scanned on port 80 as well and found out that _http://test.com/_ redirected to _https://test.com:443/_ (as shown in my screenshot abvoe) which is the same host in my opinion. Nevertheless, Observatory says "redirection-off-host-from-http".

**Comment by floatingatoll** [comment]
(Screenshot missing, sorry.) If http://www.test.com/ is live and serving a redirect to https://test.com/ then entering 'www.test.com' into the scanner will correctly report "redirection-off-host-from-http". To fix that, you have to redirect http://www.test.com/ to https://www.test.com/ to https://test.com/ with HSTS headers at every https: step.

**Comment by floatingatoll** [comment]
That's very curious. Are you returning Location: https://test.com/ or Location: https://test.com:443/ ?

**Comment by aosdf6dd** [comment]
It seems to be a location redirect to https://test.com:443/

See here:
![unbenannt](https://cloud.githubusercontent.com/assets/20280659/21450647/1aa8e20a-c8f9-11e6-8463-db9eba3c0ea4.png)

**Comment by wanshuo168** [comment]
@floatingatoll  @aosdf6dd thanks for your reply, the "test.com" is not a real domain, it's just a sample.
Yes, I use the method: scan('www.test.com');  and it worked; and scan('www.test.com', http_port=80);  but it failed. 
I'm very sure the website can redirect to https url, when I type www.test.com or www.test.com:80 in the IE browser, the browser can redirect to https://www.test.com.

**Comment by floatingatoll** [comment]
Alright. I'm not sure what other questions to ask, maybe the project author will know what's up when she sees this.

If either of you would be willing to share the actual site name being scanned privately, so that we can scan it and see what's going on and try to reproduce and repair this for you, that would be a useful thing to be able to do here. I'm atoll AT mozilla DOT com if that's an acceptable thing, otherwise we'll try to figure this out from the evidence above.

**Comment by aosdf6dd** [comment]
The host I'm using is not reachable from the Internet and I couldn't find a similarly behaving one. shodan.io is the best search engine to lookout for such servers, but I couldn't identify one, as there are several requirements:
- Certificate chain needs to be valid (otherwise you get a different output which has a higher priority)
- Server needs to be accessed via a domain name, because it is not possible to scan IP addresses

There **might** be e general problem in Observatory: (In response headers/bodies) It should consider HTTPs URLs  without port and HTTPs urls with port 443 as the same. The same way it should understand HTTP urls without port as equal to HTTP urls with port. The string representation might be different, but logically the targets are the same.

**Comment by floatingatoll** [comment]
Yeah, that's my thinking as well. I'll keep trying to find some hint of
what's up in the code.

**Comment by marumari** [comment]
I know what's happening here, it shouldn't be too painful to fix.
