### ISSUE TITLE
"Session cookie set without using the HttpOnly flag"

### ISSUE THREAD

**Issue by fipsofant** [mozilla/http-observatory#215]
Hi,

just checked session cookies.
Got: "Session cookie set without using the HttpOnly flag"
But Server Raw Header shows: "Set-Cookie	secure; httponly"

**Comment by floatingatoll** [comment]
This is working out well for other sites, so there's likely some sort of RFC violation in the headers of the site you're checking.

Are you permitted to share with us either a complete Set-Cookie value (copy-pasted from the results) or the hostname of the site you're scanning, so that we may further assist you?

**Comment by fipsofant** [comment]
Sure you can check it on https://portal.fuerst.it

**Comment by LeSuisse** [comment]
Out of curiosity I have taken a look at your headers:
```
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 22 Feb 2017 20:48:25 GMT
Content-Type: text/html
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/<version>
Set-Cookie: PHPSESSID=randomstring; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Vary: Accept-Encoding
Strict-Transport-Security: max-age=63072002
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Set-Cookie: secure; httponly
```

The header `Set-Cookie: secure; httponly` does not respect [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.1), a name and a value are expected.

**Comment by floatingatoll** [comment]
Yeah, it looks like when you set the secure and httponly flags, you may have accidentally deleted the cookies themselves, and replaced it with a cookie whose name is (approximately) "secure", lacking the secure property as a result.

It should looke more like ```Set-Cookie: cookiename=cookievalue; secure; httponly```. Unfortunately, adding a separate header won't do that. I think the issue is above:

```Set-Cookie: PHPSESSID=randomstring; path=/```

To fix that one, you need to look at setting session.cookie_secure(BOOLEAN) and session.httponly(BOOLEAN) in your php.ini.

http://www.php.net/manual/en/session.configuration.php#ini.session.cookie-secure

**Comment by fipsofant** [comment]
Thanks for your reply.
Well the origin Webserver is a Apache, Nginx is just the reverse proxy.
Nginx add the header, like for HSTS or X-XSS-Protection...

**Comment by tisba** [comment]
We are seeing a similar issue. Our `Set-Cookie` header looks like this:

```
_fejo-next_session=RlZRVmdJcitmUmo5MmtUc0s0SHJUOUJaZTlveGVOTFE3cWt1c1pqUUl4a01nT1phVFJVSDhheWR2aUFhZkVHMWpxbnluaXgwTlUzODg0ZW1vWmVrdTFlaXZuRTRTalFHUVZlQmF4MXBPOEx2OU5leGRYbzFSUzF0VnlTUDFhSVZwY2xwd2hkQ1V1NHM4SkNoK2hvL2d0aHBGY0NsZ3RaNHM0R0FvRGRKT3N6bE5oVGhWYytscjRnZVBxaDd3WDlrekNXVU5zQlh1ZGJXMU5YdXJ4cDl5QT09LS1JUzZubzBzWDBPZHZOci9QS3NsanNnPT0%3D--740a33782f168d4bfa; path=/; secure; HttpOnly
```

I found some vague references that hyphens in cookie names can cause problems in some implementations (but should be permitted according to the RFC).

We are currently getting: "-40 | Session cookie set without using the Secure flag or set over http" :-/

Any idea, @floatingatoll?

**Comment by april** [comment]
tisba, just saw this -- are you still having issues?

**Comment by tisba** [comment]
@april yes, the problem still exists. I just did another scan of `https://www.fejo.dk` with the same result.

**Comment by floatingatoll** [comment]
That site's cookie header parses correctly in Firefox:

<img width="145" alt="screen shot 2018-01-21 at 10 55 41" src="https://user-images.githubusercontent.com/92684/35197778-b889349e-fe99-11e7-8d70-6438b94c1871.png">

**Comment by april** [comment]
It's not entirely obvious from the UI, but Observatory tracks cookies that are set across its entire session, which is about a half-dozen requests are so. Here it sees three cookies:

```json
        "_fejo-next_session": {
          "domain": "www.fejo.dk",
          "expires": 1611330591,
          "httponly": true,
          "max-age": null,
          "path": "/",
          "port": null,
          "samesite": false,
          "secure": true
        },
        "_fejo_session": {
          "domain": ".www.fejo.dk",
          "expires": 1611330593,
          "httponly": true,
          "max-age": null,
          "path": "/",
          "port": null,
          "samesite": false,
          "secure": false
        },
        "vwo": {
          "domain": "www.fejo.dk",
          "expires": 1521820191,
          "httponly": false,
          "max-age": null,
          "path": "/",
          "port": null,
          "samesite": false,
          "secure": false
        }
```

It's `_fejo_session` that is triggering the error. Sorry that the raw server headers thing can be a bit confusing.

**Comment by tisba** [comment]
Ah, thanks, @april!

The page is a bit complicated with legacy components. I totally forgot that there are other (not yet properly configured) parts involved.

**Comment by gusarov** [comment]
Can you clarify a bit, what request is issued to check Set-Cookie headers? A request to the root page?
If so - that's effectively kills caching, i'm not considering this for SPA, how can I check my cookies then?

**Comment by april** [comment]
Yes, the Observatory only checks the root page (as well as some other weird ones, like `crossdomain.xml`), over HTTP and HTTPS.

If you want to check non-root pages, it's very easy to do with the Observatory local scanners, as documented in `README.md`.

**Comment by gusarov** [comment]
Well, SPA don't have other pages anyway. Actually I'd be glad to see an observatory that checks real session id, i.e. that is actually running API calls and logging-in using public demo user account. An optional data for this can be provided in an additional static files like '/observatory.json'.
Ideally this should be not just api routes, it should be html inputs and buttons ids to run actual client-side scripts for making this api calls. But this is way too complex.
What I did is just a hack... I rerutrn Set-Cookie for a call to crossdomain.xml (or similar), and this gives an extra points to those who don't deserve them... But I can't get those points the other way since session cookie happens for API calls, not for the only HTML page loading (that is served from CDN cache).

**Comment by april** [comment]
Yeah, I would love to do more in-depth things, but driving headless browsers is very expensive in computing costs and complexity.  :(
