### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by ssx** [mozilla/http-observatory#229]
Firstly, this is an immensely brilliant project.

I'm working on a system that will batch test domains over a period of time for our own sites and clients. Part of what I'm hoping to do is monitor for changes in scores and when critical things fail. 

My aim is to use observatory to run these scans, likely in a Docker container, however I've seen the CLI version now. 

My questions are these:

 - Is there any difference in the reporting provided by the CLI vs the main project
 - In the JSON responses, is everything present in the report that is on the main website (ie, third party results)
  - Will there be any license implications in using this in a commercial project?

I appreciate the time and effort taken to read and reply to this, if its better directed to somewhere else, please let me know.

**Comment by floatingatoll** [comment]
By "CLI", do you mean the mozilla/observatory-cli CLI scanner tool, or the mozilla/http-observatory CLI local scan tool?

**Comment by ssx** [comment]
I was referring to mozilla/observatory-cli (npm package), but could easily use the local scan tool if its more populous.

**Comment by floatingatoll** [comment]
I don't mean to instruct you to do either, just helping the conversation understand what you were using.

**Comment by ssx** [comment]
Is there any difference between the two in terms of functionality? My main aim is to get a JSON version of what is shown on the observatory website.

**Comment by april** [comment]
Basically everything uses the same underlying code and should all return the exact same scan JSON.  There might be differences in the plaintext ("report") output, but the JSON results are identical across everything.

Third party integrations are *only* on the website; they're not integrated into the Observatory tooling itself.  If you wanted to use various third parties, you'd need to talk with them individually.  Many of them support commercial integrations, but would charge for it.

There's no problem with using either the public instance or your own local or hosted instance.  If you are scanning a lot of websites and generating a lot of load, I would ask that you use a local/hosted instance.  The only real difference between the public version and a local version is that the public version will get you access to a site's grade history (since the public website has a lot of history).  You can get history with a hosted instance, but it would obviously only date back to when you started.

As for license implications, I can't really speak to that, other than to say that you would need to comply with the MPL2 license should you integrate the code in your product.  If you choose to use the public API, please make sure you follow our terms-of-use, which are pretty lenient:

https://observatory.mozilla.org/terms.html

Please let me know if that answers all your questions.  Thanks!

**Comment by april** [comment]
FWIW, most companies that are scanning internally use the Python library or `httpobs-local-scan` and most public sites that use the Observatory for scanning public websites simply call our API directly or use `observatory-cli` and parse the JSON.

**Comment by ssx** [comment]
Comprehensive answer, I'll go for the `observatory-cli` route I think, does that work completely independently from the public and/or a hosted version? If it's standalone, I can just pop that into a worker queue and this becomes quite a bit easier.

If I do go for the public instances and API route, I'll include contact details in the user agent in the event any issues do arise.

Once again, thank you for such a great project.

**Comment by floatingatoll** [comment]
If you want completely independent, use the httpobs-local-scan path.
http-observatory/README.md has a section explaining how to use the local
scanner either from Python code or from the CLI.

**Comment by ssx** [comment]
Great! Many thanks to the two of you. 🥇

**Comment by floatingatoll** [comment]
It's all thanks to April, I just do bits of triage to help with the
paperwork.

**Comment by april** [comment]
Thanks, @floatingatoll.  @ssx, good luck!  I always love to hear and share success stories, so if you have great luck with it, let me know so I can share it on Twitter and the like.  If you want, that is.  :)
