### ISSUE TITLE
Support for different SSH ports

### ISSUE THREAD

**Issue by Hativ** [mozilla/http-observatory#332]
It would be nice if the port for SSH could be entered, because many changed the SSH port.

**Comment by floatingatoll** [comment]
The website intentionally restricts scans to port 22/tcp only, and will not permit scans of non-default ports (either for SSH, or for HTTP/HTTPS) for safety reasons.

However, you can run the scanner component of the Observatory locally if you wish. The `README` contains details on how to run the command-line scanner, which will permit you to initiate scans of non-standard ports from a computer under your own control (rather than our servers).
