### ISSUE TITLE
Cookies: `SameSite` attribute

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/http-observatory#64]
Now that the `SameSite` attribute is supported in Chrome 51:

https://www.chromestatus.com/feature/4672634709082112

Can we get extra points if the cookie includes `SameSite=Strict` or `SameSite=Lax`

https://tools.ietf.org/html/draft-west-first-party-cookies-07

**Comment by gavinmporter** [comment]
Support for the SameSite attribute is being added to Firefox 58. The attribute is an excellent mechanism for CSRF protection is browsers that support it.

To avoid confusion with the points calculation in the current Cookies section, I suggest it may be simplest to have a specific SameSite setting that is totally separate from Cookies. 

How about a points value of +10 if Samesite is defined so that it initially represents a bonus as not many people have it enabled.

**Comment by april** [comment]
I think it's going to be confusing to a lot of people to have both a Cookies test and a SameSite Cookies test. I'm okay with granting a bonus to those who are using it and penalizing CSRF tokens without it, but I think that could be rolled into the existing cookies test without adding too much confusion.

**Comment by april** [comment]
Alternatively, I could have a penalty for sites that set cookies without SameSite. For example:

+5 Cookies all use SameSite
0 No cookies set
-1 Cookies set using Secure and HttpOnly properly, but not being explicit SameSite
-20 CSRF token set without SameSite

The only downside with this approach is that there's no easy way to be explicit about wanting your cookies to be sent cross-origin, so that a site that did want their cookies to be sent cross-origin would be penalized even if they wanted them to be.

Thoughts?

**Comment by craigfrancis** [comment]
I’d be tempted to start with a very simple +5 if one cookie used SameSite, and show it as a suggestion if it’s not found - just so developers become aware of it.

I would love for there to be a negative score, especially on a cookie that’s clearly used for CSRF (guessing by name?) - but I don’t think many programming languages are ready for it yet; e.g. PHP:
https://wiki.php.net/rfc/same-site-cookie

**Comment by april** [comment]
I would love if folks could take a look at #313. If everyone is okay with it, I'll update the scoring documents and push it out.

Thanks!

**Comment by craigfrancis** [comment]
I've taken a look, and I'm happy with it... but I've not got a local instance running to test it properly (sorry, don't have the time at the moment).

:-)

**Comment by april** [comment]
It's been a long journey, but this is now implemented and live. Please let me know if you run into any bugs, and thanks!

**Comment by craigfrancis** [comment]
Thanks again April, really appreciate everything you do :-)
