### ISSUE TITLE
Check for contribute.json seems unwarranted

### ISSUE THREAD

**Issue by jgraham** [mozilla/http-observatory#81]
Most of the checks in HTTP Observatory are reasonable security best-practices that alter the functioning of the site. However the check for a `contributing.json` file seems markedly different; it doesn't represent any kind of accepted best practice and the presence or absence of such a file doesn't materially alter the functioning of the site in any way.

Although I agree that the goal of making information about the provenance of a site available is laudable, the approach taken by `contributing.json` follows a design pattern of relegating metadata to some default-invisible location. This has been tried in many contexts on the web and had repeatedly failed (in the sense that tools which intended to consume such data found that the data quality was so low that they could not reliably do so). Unless the data is visible in the site UI people will forget to update it when reality changes, and the file will become defacto untrustworthy. Scoring people on the presence of the file without any way to validate that the information contained therein is actually meaningful does not seem like it will help with this problem. Therefore I suggest that this check is removed from the tool and that the approach to surfacing this (potentially useful) data reevaluated, taking into account the fact that people are much more likely to keep it up to date if it is actually visible on their site.

**Comment by edmorley** [comment]
In addition to the file contents becoming stale, I'm not sure how useful it is from a security perspective.

An automated security tool won't be able to open PRs or file issues, since it will want to disclose vulnerabilities responsibly. Even if sites have a bugzilla URL in `contributing.json`, there's no enforcement as to which URL they'll have specified or guarantee that the security groups for that component are set up correctly for a tool to use. As such, it seems like a human is always going to end up as part of the process anyway.

One argument for the file, might be that some more commercial sites aren't able to have a "Source", "Issues" or "Security" footer link, however given that:
a) https://www.contributejson.org/ states that the file is intended for open source projects,
b) http-observatory only enforces `contributing.json` for Mozilla properties (which are typically open source and should be linking to Source/Issues in their footer anyway)
...it doesn't seem like it should be hard for people to find how to report issues regardless.

Perhaps an alternative is to have http-observatory check if the homepage contains a link with link text or target relating to source/bugs/issues/bugzilla/github instead?

Or if we're going to try and encourage the web to implement a new best-practice, reducing the scope to "make it easy to find out how to report security issues" might be more realistic? eg instead mandate that Mozilla properties have a human-readable page at `/security` (or whatever name) that displays (or redirects) to the canonical (and up to date) details for that project? (eg for Treeherder I guess the target would be either the wiki page, GitHub repo or Read the Docs page).

**Comment by marumari** [comment]
The check for contribute.json is only for Mozilla sites currently; the website completely hides the check and test numbers if it's not a Mozilla site.

Checking for contribute.json is in there now for Mozilla sites because:

- We have thousands of sites
- We have no idea who many of them belong to

This makes security bug triage take a very long time for the more obscure sites.  The tool isn't encouraging the world to adopt it; it doesn't even display information about it for the vast majority of users.

**Comment by marumari** [comment]
Here is a check for my own personal website:

https://mozilla.github.io/http-observatory-website/analyze.html?host=pokeinthe.io

A regular user wouldn't even know that contribute.json exists.  I may in the future give +5 for non-Mozilla sites that do have it, but that's for when I have more time.  :)

**Comment by jgraham** [comment]
Even for Mozilla sites, the problems I mentioned still exist. If you look at intranet, mana, wiki, MDN and a bunch of other Mozilla sites that contain human-readable documentation, you will see that we are terrible at keeping this kind of information up to date even when it is trivial to change and world-visible. Centralizing it in a hidden json file that people will add once and forget about seems like a poor solution to this problem.

**Comment by marumari** [comment]
If you have a better solution and tool than what we currently have, I'd be happy to start using it.  :)

**Comment by edmorley** [comment]
> If you have a better solution and tool than what we currently have, I'd be happy to start using it. :)

Source/issue links in the site footer or help menu. Which Treeherder already has.

Plus see my previous comment :-)

**Comment by edmorley** [comment]
What would help here, is a clear definition of the problem that's trying to be solved, specifically from a http-observatory perspective.

ie:
"As a security researcher, when my automated tools find an exploit, the sites often don't have any contact information, so I don't know where to report them"

In this problem statement, it would be useful to state whether the problem is primarily with automation or humans or both.

**Comment by marumari** [comment]
That has even more issues, namely that it's absurdly hard to do programmatically.  Are you suggesting we force each Mozilla site to have specific ids for these links and footers?

**Comment by edmorley** [comment]
I'm saying you can't do this programatically already, given responsible disclosure.

It really feels like the full comments above haven't been read, which is pretty frustrating.

**Comment by marumari** [comment]
The HTTP Observatory is a programmatic, automatic scanning tool?

**Comment by jgraham** [comment]
You can programmatically scan to check that a thing exists. You can't programatically determine that the data you find is correct or, in the case of reporting security vulnerabilities, make use of that data even if it does happen to be correct.

FWIW the idea of mandating specific classnames for metadata has a long history e.g. [microformats](http://microformats.org/wiki/about) use exactly that approach. I don't see why it's considered an unreasonable idea.

**Comment by marumari** [comment]
I suspect the problem is that you aren't understanding what the problem is?

Here is the problem:

"The Mozilla information security team has to triage dozens of incoming security bugs filed under Websites -> Other each week.  We have no simple way of finding out who owns (or owned) a given website or product.  This means that triaging bugs can take far longer than they would otherwise, and puts our infrastructure at risk."

And is why the tooltip for contribute.json specifically says:

"Having a contribute.json file on the root of your website allows Mozilla's information security team to more quickly triage incoming security bugs."

Having a contribute.json file there at least gives us a start at finding out who to contact.  If all the contacts in there no longer work at Mozilla, we can at least look at who their bosses were and get a contact that way.

**Comment by marumari** [comment]
I'd be happy to chat with you over Vidyo, which is probably going to be a lot more useful than going back and forth over GitHub.

**Comment by jgraham** [comment]
OK, but that doesn't address the original point which is "mandating that this metadata be hidden in a json file vastly increases the chance that it will be incorrect vs a system that means that the data is also visible when accessing the site using a web browser".

**Comment by marumari** [comment]
I don't disagree that it's hard to keep this stuff up-to-date.  In the future, I hope to add checks to verify that the information is valid.

That said, I should note that the stuff that tends to get out of date the fastest -- such as contact information -- isn't checked by the HTTP Observatory.  It's pretty rare for a production URL, Bugzilla category, or GitHub repo URL to change.

It only checks for these keys: name, description, participate, bugs, and urls.  Looking at Treeherder, are any of those likely to become out of date that quickly?  Obviously participate -> irc-contacts can become outdated quickly, but the Observatory doesn't enforce or check those.

I would be happy to accept a PR with code that checks for the things you suggest in lieu of a contribute.json.  :)

**Comment by edmorley** [comment]
> "The Mozilla information security team has to triage dozens of incoming security bugs filed under Websites -> Other each week. We have no simple way of finding out who owns (or owned) a given website or product. This means that triaging bugs can take far longer than they would otherwise, and puts our infrastructure at risk."

Are you wanting specifically to find out individuals or the Bugzilla/GitHub components?

`contributing.json` seems like a poor way of finding out individuals, since:
* listing emails just opens people up to spam
* emails listed might not match those used on Bugzilla, so the user search will turn up empty
* listing bugzilla ":foo" style names can hit false positives/likely still needs human intervention
* even if you know the user, it would be better to move the `Websites :: Other` bugs to their actual component, so you still need to know what that is

It seems like the following might be a better way of always ensuring knowing where to file a bug:
1) Require that all *.mozilla.org properties have a Bugzilla component, even if it's just for security and they use GitHub for everything else
2) If the Bugzilla component isn't one of the one that has the domain in the component name (ie not like "Websites :: login.mozilla.com"), add the domain name to the Bugzilla component description. 

-> Then when filing bugs you just start typing the domain name into the "find product/component" field on https://bugzilla.mozilla.org/enter_bug.cgi and the result appears.

That way you both have somewhere you can file a private bug (unlike if you rely on someone's GitHub issues link in `contributing.json`), and if the Bugzilla component later gets moved, you don't have a stale link in `contributing.json`, and the component description means you can still find it.

**Comment by marumari** [comment]
Some applications that do a great job of keeping that stuff up to date (like addons) have IRC contacts in there, which can be very helpful.  But mostly we're concerned about finding the Bugzilla/GitHub location for us to file bugs.  You'd be surprised how hard that can be to track down for many sites.

**Comment by marumari** [comment]
And yes, I would absolutely love to have a Websites :: X category for each website we have at Mozilla.  Unfortunately, we have some ~1000 or so of those sites, created over the last 20 years, of which maybe 10% have Bugzilla components.

We'd need to create an additional 900 Bugzilla categories and track down owners of each of those sites.  It's possible, but very easily could be a multi-year project for a number of people.

**Comment by edmorley** [comment]
> We'd need to create an additional 900 Bugzilla categories and track down owners of each of those sites. It's possible, but very easily could be a multi-year project for a number of people.

That's probably easier than getting all 1000 sites to add a contribute.json, if some really aren't maintained :-)

Fwiw I have permissions to add new Bugzilla components, if you ever need any creating. Just file in bugzilla.mozilla.org::Administration and CC me (though the Bugzilla team themselves are pretty responsive too). Plus if there were a large batch, I'm sure the Bugzilla people would be happy to script it.

**Comment by floatingatoll** [comment]
Is this issue asking that we *not* test for and validate the presence of *any* Mozilla standard mechanism for publishing site metadata?

Or, is this issue asking that we *change* the standard mechanism tested for by the observatory?

**Comment by jeffbryner** [comment]
A little more background: 

https://www.contributejson.org/ is a mozilla standard adopted by mozilla.org (literally our bedrock). The use cases for the standard are part of that site. 

This observatory project is all about enacting other standards so we can be consistent, predictable, repeatable. Some projects use github, some bugzilla, some jira, etc. 

Working bugs in the bounty program is largely about tracking down who owns a site, who runs a site, where issues are filed, etc. Contribute.json shortcuts this and eventually allows for automation. 

Not having a clear way to contact a site owner, find the source, etc is a sign of a poorly maintained site in the same way that lacking CSP when XSS is our top vulnerability is also a sign of a poor site. 

The suggested alternative of source/issue links in the site footer or help menu will quickly become a branding issue on our main sites and is not an existing standard. Adopting the mozilla contribute.json standard for mozilla sites avoids branding issues and allows for us to sync.

**Comment by jgraham** [comment]
It seems to me that the idea of having some way of identifying points of contact across Mozilla properties is reasonable. However I don't think that the substantive arguments against the `contributing.json` approach have been seriously considered. The argument that `constributing.json` is a "standard" is particularly uncompelling; I have seen a large number of hidden metadata standards in the past, many backed up by large standards organisations. The success rate of these has been very low, basically limited to cases where the "hidden" data was surfaced by some widely used external tool in a way that had direct impact on the site (notably search engines).

If a goal here is that third parties are able to report security issues with our website in the correct place, then having a policy of linking to that correct place in some way that a human can find using a web browser seems even more important. Not having such a link clearly seems like an example of a "bad site", even if work is needed to ensure it works with design considerations.

**Comment by marumari** [comment]
> If a goal here is that third parties are able to report security issues with our website in the correct place, then having a policy of linking to that correct place in some way that a human can find using a web browser seems even more important. Not having such a link clearly seems like an example of a "bad site", even if work is needed to ensure it works with design considerations.

This is not the goal.  It's great if it happens, but it's not really intended really for third parties nor for automated bug submission.  Third-parties will report through the existing website bug bounty process as it is, and my team will route the bug to the correct place.  Having a contribute.json helps my team get the bug in the proper place quickly.

**Comment by marumari** [comment]
Penalty reduced in #85.

**Comment by edmorley** [comment]
So I was thinking about this some more today.

Our main concerns about `contribute.json` are:
* that it's frustrating to have to duplicate information that is already kept elsewhere (eg `package.json`)
* that it's much less likely people look at `contribute.json` on a regular basis (since it's less well known and not often opened like say `package.json` is for dependency updates), so inaccuracies may get corrected less promptly than if the canonical metadata source was `package.json`

Perhaps a compromise here is if Mozilla tooling (both the security team tools and HTTP observatory) checked not only `<site_root>/contribute.json` but also other known existing metadata sources (such as `<site_root>/package.json`, or similar for other languages/stacks - eg `setup.py`). 

Whilst not every Mozilla property would have their repo deployment set up in such a way that these file would be accessible in the site root, a proportion will already (plus this would still aid tools that use the GitHub repos directly). Doing this in fact may result in increased metadata coverage, given the long tail of sites that will never get around to adding a `contribute.json`.

Thoughts?

**Comment by edmorley** [comment]
Or another option might be to provide libraries for a handful of languages/stacks that parse the metadata available to generate contribute.json automatically. eg a nodejs package on npm that reads package.json and can either be used via the CLI to save the relevant metadata to contribute.json or else via an API that returns the json string for use in eg a webpack build.

**Comment by jeffbryner** [comment]
Maybe I can add some context? The primary use case here for a > B+ rating with contribute.json as an attribute of the score is for a site to enter the bug bounty program. When a bug is submitted, we don't want to have to guess who might be responsible for addressing the bug. Hundreds of sites, lots of bug submissions, etc. 

Not opposed to looking at multiple things, but package.json seems more about packages that make up the site rather than the site owners. When a sec-critical is submitted, we want the shortest path to the owners of the site in an automated, repeatable, auditable way.

**Comment by floatingatoll** [comment]
Looking at the spec, package.json offers a { bugs: url/email } property
that I would accept as barely sufficient here. The word "security" is not
present anywhere in the spec I read, though:

https://docs.npmjs.com/files/package.json

**Comment by floatingatoll** [comment]
(Not "barely" as in "intolerably", but as in "compared to our homebrew JSON
file, it is far less information and with less metadata tagging, but STILL
meets the need described for a point of contact.". I mean no insult, and
apologize if I misphrased badly.)

**Comment by april** [comment]
For most websites, `package.json` and `setup.py` aren't accessible.

Bedrock, for example, has both a `package.json` and `setup.py`, but you can only see them in their GitHub repository. I honestly can't think of any website where either one of these files are visible or easily findable via a web crawler/bot. I would think that modifying their build process to put them somewhere retrievable (`.well-known/package.json`, maybe?) or to programmatically generate `contribute.json` would actually be a lot more work than simply creating `contribute.json`.

I'm not in any way wedded to `contribute.json`, but it is our standard and a decent number of our sites already implement it, and it is helpful:

https://riskheatmap.security.mozilla.org/observatory/index.html

If you can come up with a solution to the problem that doesn't have the same problems as the existing solution, I would honestly be really happy to deprecate `contribute.json` and move to something else. It just seems that every option is equally lousy, including the one we currently use.  :\

**Comment by edmorley** [comment]
> Not opposed to looking at multiple things, but package.json seems more about packages that make up the site rather than the site owners.

Ah, to clarify - it's common in the javascript ecosystem to use package.json as a way to embed additional settings/metadata for both libraries/packages and entire apps (the name `package.json` is a bit misleading in that regard). 

> Looking at the spec, package.json offers a { bugs: url/email } property that I would accept as barely sufficient here.

Those fields are only recommended minimums, users aren't limited to just those.

> Bedrock, for example, has both a package.json and setup.py, but you can only see them in their GitHub repository. I honestly can't think of any website where either one of these files are visible or easily findable via a web crawler/bot. I would think that modifying their build process to put them somewhere retrievable (.well-known/package.json, maybe?) or to programmatically generate contribute.json would actually be a lot more work than simply creating contribute.json.

I agree that many sites won't surface those. However sites adding support for `contribute.json` have to (a) add the file, (b) in many cases set up routes for it or add to the build system, whereas for say package.json they'd only have to do (b), and the file would be more likely to stay up to date.

> It just seems that every option is equally lousy, including the one we currently use. :\

Yeah fair point :-)
