### ISSUE TITLE
Site down error for IPv6-only website

### ISSUE THREAD

**Issue by oskar456** [mozilla/http-observatory#91]
Trying to check an IPv6-only website like www.doesnotwork.eu on https://observatory.mozilla.org/ results in "Site down" error message.

According to [this Twitter conversation](https://twitter.com/spazef0rze/status/769194682199007232), this issue could probably be solved by implementing ELB in front of the instance.

**Comment by jeffbryner** [comment]
Seems more an issue in the data center hosting the scanners. They aren't in AWS since it violates the terms of service.

jbryner@observatory-scanner1:~$ wget doesnotwork.eu
--2016-08-27 21:30:45--  http://doesnotwork.eu/
Resolving doesnotwork.eu (doesnotwork.eu)... 2001:1528:132:70::d0e5
Connecting to doesnotwork.eu (doesnotwork.eu)|2001:1528:132:70::d0e5|:80... failed: Network is unreachable.

@marumari seems like a job for webops/netops?

**Comment by floatingatoll** [comment]
Not much Webops can do to provision IPv6 to you, but if you're using the
proxy cluster, ask Systems team to ACL it; otherwise, ask Netops to
provision <insert hostname here> a native IPv6 address and gateway (and
define your inbound/outbound policy) and they'll provide you the necessary
info.

 - R.

**Comment by mpurzynski** [comment]
Scanners don't have IPv6 address assigned, native IPv6 is supported in this subnet so open a NetOps bug and you'll ride IPv6 in no time.

**Comment by marumari** [comment]
We have gone ahead and added IPv6 support to the scanners, and now I am able to scan www.doesnotwork.eu.  Note that the actual website (observatory.mozilla.org) still lacks an IPv6 address due to limitations in AWS, but that is a separate bug.

Please let me know if you have any more issues, and thanks so much to you for reporting the bug and for @mpurzynski for helping me get the IPv6 stuff going.
