### ISSUE TITLE
Allow testing with IP, Port and Hostname specified separately to allow testing of servers before they go live

### ISSUE THREAD

**Issue by taladar** [mozilla/http-observatory#99]
It would be useful if one could specify the host and port to connect to and the hostname to send in TLS SNI/HTTP Host Header separately to allow the testing of a server before the DNS name is configured to point to the host. This would allow the testing of new installations and fixing errors before they become the production environment.

**Comment by jvehent** [comment]
You can't scan TLS by IP, it breaks certificate validation, so this is a no go at least for the TLS part of the observatory.

**Comment by taladar** [comment]
Of course you can scan TLS by IP. I do it all the time for e.g. certificate expiry checks via
`openssl s_client -connect <ip>:<port> -servername <host>`. Of course certificate validation needs to act as if the given hostname pointed to the given IP but that is the whole point of a pre-production check anyway, to see if everything will work correctly once it does point there.

**Comment by jvehent** [comment]
You're missing my point: you cannot verify the validity of a certificate by scanning by IP, so the TLS observatory will always give you a poor grade because it sees an untrusted certificate.

**Comment by taladar** [comment]
If you give it an expected certificate subject name (hostname) and an IP and port, in what way can it not validate the certificate against that name?

**Comment by jvehent** [comment]
You theoretically can, but it's information that needs to be passed all the way down to the scanner. It might be easier for @marumari to implement on the HTTP scanner than for me to implement it on the TLS scanner.

In practice, most organizations use a staging domain with a valid certificate to do QA, so I'm not sure if there is a lot of value in supporting IP based scanning.

**Comment by taladar** [comment]
The problem with the approach of using another certificate on another virtual host on potentially a completely different server is that it does not really check if all the settings are correct on the actual production system about to go live. It just checks if a system with dozens of different configuration options (even when removing duplication via configuration management) is set up correctly.

**Comment by marumari** [comment]
The Observatory website (and HTTP Observatory itself) don't allow scanning by IP address for this very reason: every HTTPS would fail validation. It could be done with some `requests` library hacking, but it would be ugly.

And in theory, it could be added to the TLS Observatory API, eg, when you submit the POST request you could have a `force_ip` field.

All that said, I would rather focus work on making it easier to setup private Observatory installations.  With your own installation, you could simply set the IP address of a host in /etc/hosts (or via your own DNS server) and scan to your heart's content.  You can already do that now, but it involves a lot of leg work.

This also a pretty unusual use case too -- most people in this situation just request multiple certs (or have a cert with multiple subjectAltNames), such as observatory.mozilla.org and observatory-staging.mozilla.org, and test that way.

I'm going to close this because given my current cycle limitations that I don't think I would be able to get to it for a very long time.
